provider = "gdrive"
sync_interval = "1m"
versioning = true
max_versions = 3
ignore = [".git", "*.log", "node_modules"]

[[sync_paths]]
  path = "C:/Users/rish/AppData/Roaming/Sekiro"
  label = "Sekiro"
